FROM python:3.7-alpine3.7
LABEL maintainer="Igor Nehoroshev <harry@hashdivision.com>"
RUN mkdir -p /clothobserve
COPY requirements.txt /requirements.txt
WORKDIR /clothobserve
RUN pip3 install -r /requirements.txt

EXPOSE 5000

CMD sleep 10 && gunicorn --reload -b 0.0.0.0:5000 main:SERVER