FROM python:3.7-alpine3.7
LABEL maintainer="Igor Nehoroshev <harry@hashdivision.com>"
RUN mkdir -p /clothobserve /tests /docs
COPY test-requirements.txt /requirements.txt
COPY clothobserve /clothobserve/
WORKDIR /clothobserve
RUN apk add --update alpine-sdk
RUN pip3 install -r /requirements.txt

EXPOSE 5000

CMD sleep 10 && coverage run --source=/clothobserve -m unittest discover -v -s /tests/ && coverage report -m && sphinx-apidoc -f -o /docs/source/ /clothobserve/ && cd /docs && make html && cd /clothobserve && pylint --generated-members=id,objects,StringField,DateTimeField,BooleanField,ReferenceField,ListField,IntField,LazyReferenceField main.py endpoints data utils logic