FROM python:3.6-alpine3.7
LABEL maintainer="Igor Nehoroshev <harry@hashdivision.com>"
RUN mkdir -p /clothobserve /tests
COPY quicktest-requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
WORKDIR /clothobserve

EXPOSE 5000

CMD sleep 10 && coverage run --source=/clothobserve -m unittest discover -v -s /tests/ && coverage report -m